### ISSUE TITLE
Stoped working?

### ISSUE THREAD

**Issue by DevinThePancake** [lebbe/random_fml#1]
It's been working for me do a while but now when I try it nothing shows up like it can't find any quotes. Please fix <3

**Comment by lebbe** [comment]
Looks like fmylife.com is down:


http://www.fmylife.com/random

**Comment by DevinThePancake** [comment]
Oh shit my bad wew I checked one time and it was up but I didn't refresh the site, well thanks anyway

**Comment by DevinThePancake** [comment]
It started happening again so I checked the site and it was online, so I've tested for 2 days and it's not working and the website has been up :/

**Comment by lebbe** [comment]
Yes, look at that!

They have updated design on their homepage. This influences my crawler.

I have updatet random_fml to version 1.1.0. Please update! :)

**Comment by DevinThePancake** [comment]
Awesome dude thanks! I went testing and it works but it's weird because on some quotes it will cut off and do ... and others just do the whole thing

**Comment by DevinThePancake** [comment]
Also it seems to repeat if you wait like 3 min and start from like the beginning like it's a list, but idk that might be a fmylife issue

**Comment by lebbe** [comment]
You are correct on both accounts. Both are an issue with what fmylife.com returns. Perhaps they do it intentionally, wanting people to visit their homepage instead of crawling their site.
